# 这些是受支持的资助平台

github: # 替换为你的GitHub Sponsors用户名
# patreon: # 替换为你的Patreon用户名
# open_collective: # 替换为你的Open Collective用户名
# ko_fi: # 替换为你的Ko-fi用户名
# tidelift: # 替换为你的Tidelift平台名称
# community_bridge: # 替换为你的Community Bridge项目名称
# liberapay: # 替换为你的Liberapay用户名
# issuehunt: # 替换为你的IssueHunt用户名
# otechie: # 替换为你的Otechie用户名
# lfx_crowdfunding: # 替换为你的LFX Crowdfunding项目名称
# custom: # 替换为你的自定义URL数组

